/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Analyze: typeof import('./src/components/Analyze.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Levels: typeof import('./src/components/Levels.vue')['default']
    List: typeof import('./src/components/List.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    PinyinSelect: typeof import('./src/components/PinyinSelect.vue')['default']
    Quiz: typeof import('./src/components/Quiz.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
  }
}
